"""Transform code generator — emit Python (SQLAlchemy) or TypeScript from a reconciliation result."""

from backend.core.ir.models import Schema, ReconciliationResult, ColumnType, Table


# ── Type maps ─────────────────────────────────────────────────────────────────

_SA_TYPE: dict[ColumnType, str] = {
    ColumnType.INTEGER:   "Integer",
    ColumnType.BIGINT:    "BigInteger",
    ColumnType.SMALLINT:  "SmallInteger",
    ColumnType.FLOAT:     "Float",
    ColumnType.DOUBLE:    "Float(precision=53)",
    ColumnType.DECIMAL:   "Numeric",
    ColumnType.BOOLEAN:   "Boolean",
    ColumnType.CHAR:      "CHAR",
    ColumnType.VARCHAR:   "String",
    ColumnType.TEXT:      "Text",
    ColumnType.BLOB:      "LargeBinary",
    ColumnType.DATE:      "Date",
    ColumnType.TIME:      "Time",
    ColumnType.DATETIME:  "DateTime",
    ColumnType.TIMESTAMP: "DateTime(timezone=True)",
    ColumnType.JSON:      "JSON",
    ColumnType.UUID:      "String(36)",
    ColumnType.ENUM:      "String",
    ColumnType.UNKNOWN:   "Text",
}

_TS_TYPE: dict[ColumnType, str] = {
    ColumnType.INTEGER:   "number",
    ColumnType.BIGINT:    "number",
    ColumnType.SMALLINT:  "number",
    ColumnType.FLOAT:     "number",
    ColumnType.DOUBLE:    "number",
    ColumnType.DECIMAL:   "number",
    ColumnType.BOOLEAN:   "boolean",
    ColumnType.CHAR:      "string",
    ColumnType.VARCHAR:   "string",
    ColumnType.TEXT:      "string",
    ColumnType.BLOB:      "Buffer",
    ColumnType.DATE:      "Date",
    ColumnType.TIME:      "string",
    ColumnType.DATETIME:  "Date",
    ColumnType.TIMESTAMP: "Date",
    ColumnType.JSON:      "Record<string, unknown>",
    ColumnType.UUID:      "string",
    ColumnType.ENUM:      "string",
    ColumnType.UNKNOWN:   "unknown",
}


# ── Python / SQLAlchemy ───────────────────────────────────────────────────────

def generate_sqlalchemy(
    result: ReconciliationResult,
    source: Schema,
    target: Schema,
) -> str:
    lines = [
        "# Auto-generated by SchemaSync — review before use",
        "# pip install sqlalchemy",
        "",
        "from sqlalchemy import (",
        "    Column, Integer, BigInteger, SmallInteger, Float, Numeric, Boolean,",
        "    String, Text, LargeBinary, Date, Time, DateTime, JSON, CHAR, ForeignKey,",
        "    create_engine,",
        ")",
        "from sqlalchemy.orm import DeclarativeBase, Session",
        "",
        "",
        "class Base(DeclarativeBase):",
        "    pass",
        "",
        "",
    ]

    for tm in result.table_mappings:
        tgt_table = target.get_table(tm.target_table)
        src_table = source.get_table(tm.source_table)
        if not tgt_table:
            continue

        class_name = _to_pascal(tm.target_table)
        lines.append(f"class {class_name}(Base):")
        lines.append(f'    __tablename__ = "{tm.target_table}"')
        lines.append(f"    # mapped from: {tm.source_table} (confidence {tm.combined_score:.0%})")
        lines.append("")

        for col in tgt_table.columns:
            sa_type = _sa_col_type(col)
            attrs = []
            if col.is_primary_key:
                attrs.append("primary_key=True")
            if col.is_auto_increment:
                attrs.append("autoincrement=True")
            if col.is_unique and not col.is_primary_key:
                attrs.append("unique=True")
            if not col.nullable and not col.is_primary_key:
                attrs.append("nullable=False")
            if col.default_value is not None:
                attrs.append(f'default="{col.default_value}"')
            if col.foreign_key:
                fk = col.foreign_key
                sa_type = f"ForeignKey('{fk.target_table}.{fk.target_column}')"
                attrs.insert(0, sa_type)
                sa_type = _sa_col_type(col)

            # Find original source column name for comment
            src_col_name = next(
                (cm.source_column for cm in tm.column_mappings if cm.target_column == col.name),
                None,
            )
            comment = f"  # from: {src_col_name}" if src_col_name and src_col_name != col.name else ""

            col_args = f"{sa_type}, " + ", ".join(attrs) if attrs else sa_type
            if col.foreign_key:
                fk = col.foreign_key
                col_args = f"{sa_type}, ForeignKey('{fk.target_table}.{fk.target_column}')"
                if attrs:
                    col_args += ", " + ", ".join(attrs)
            lines.append(f"    {col.name} = Column({col_args}){comment}")

        lines.append("")
        lines.append("")

    lines.append("")
    lines.append("# ── Migration helper ─────────────────────────────────────────────")
    lines.append("def migrate(source_url: str, target_url: str):")
    lines.append('    """Migrate data from source DB to target schema."""')
    lines.append("    src_engine = create_engine(source_url)")
    lines.append("    tgt_engine = create_engine(target_url)")
    lines.append("    Base.metadata.create_all(tgt_engine)")
    lines.append("")
    for tm in result.table_mappings:
        src_table = source.get_table(tm.source_table)
        tgt_table = target.get_table(tm.target_table)
        if not src_table or not tgt_table:
            continue
        class_name = _to_pascal(tm.target_table)
        lines.append(f"    # {tm.source_table} → {tm.target_table}")
        lines.append(f"    with src_engine.connect() as src_conn, Session(tgt_engine) as tgt_session:")
        lines.append(f'        rows = src_conn.execute(src_engine.dialect.statement_compiler(src_engine.dialect, None).process(f"SELECT * FROM {tm.source_table}"))')
        lines.append(f"        for row in rows:")
        col_map_items = ", ".join(
            f"{cm.target_column}=row.{cm.source_column}"
            for cm in tm.column_mappings
        )
        lines.append(f"            tgt_session.add({class_name}({col_map_items}))")
        lines.append(f"        tgt_session.commit()")
        lines.append("")

    return "\n".join(lines)


# ── TypeScript ────────────────────────────────────────────────────────────────

def generate_typescript(
    result: ReconciliationResult,
    source: Schema,
    target: Schema,
) -> str:
    lines = [
        "// Auto-generated by SchemaSync — review before use",
        "",
    ]

    for tm in result.table_mappings:
        tgt_table = target.get_table(tm.target_table)
        if not tgt_table:
            continue

        interface_name = _to_pascal(tm.target_table)
        lines.append(f"/** Mapped from: {tm.source_table} (confidence {tm.combined_score:.0%}) */")
        lines.append(f"export interface {interface_name} {{")

        for col in tgt_table.columns:
            ts_type = _TS_TYPE.get(col.col_type, "unknown")
            if col.col_type == ColumnType.ENUM and col.enum_values:
                ts_type = " | ".join(f'"{v}"' for v in col.enum_values)
            optional = "?" if col.nullable and not col.is_primary_key else ""
            src_col_name = next(
                (cm.source_column for cm in tm.column_mappings if cm.target_column == col.name),
                None,
            )
            comment = f" // from: {src_col_name}" if src_col_name and src_col_name != col.name else ""
            lines.append(f"  {col.name}{optional}: {ts_type};{comment}")

        lines.append("}")
        lines.append("")

    lines.append("")
    lines.append("// ── Migration mapper functions ───────────────────────────────")
    lines.append("")

    for tm in result.table_mappings:
        tgt_table = target.get_table(tm.target_table)
        src_table = source.get_table(tm.source_table)
        if not tgt_table or not src_table:
            continue

        src_interface = _to_pascal(tm.source_table)
        tgt_interface = _to_pascal(tm.target_table)

        lines.append(f"// Source type (from {tm.source_table})")
        lines.append(f"export interface {src_interface}Legacy {{")
        for col in src_table.columns:
            ts_type = _TS_TYPE.get(col.col_type, "unknown")
            optional = "?" if col.nullable else ""
            lines.append(f"  {col.name}{optional}: {ts_type};")
        lines.append("}")
        lines.append("")

        lines.append(f"export function map{src_interface}To{tgt_interface}(")
        lines.append(f"  src: {src_interface}Legacy,")
        lines.append(f"): {tgt_interface} {{")
        lines.append("  return {")
        for cm in tm.column_mappings:
            src_col = src_table.get_column(cm.source_column)
            tgt_col = tgt_table.get_column(cm.target_column)
            if src_col and tgt_col and src_col.col_type != tgt_col.col_type:
                cast = _ts_cast(src_col.col_type, tgt_col.col_type, f"src.{cm.source_column}")
                lines.append(f"    {cm.target_column}: {cast}, // {src_col.col_type.value} → {tgt_col.col_type.value}")
            else:
                lines.append(f"    {cm.target_column}: src.{cm.source_column},")
        for col_name in tm.unmatched_target:
            tgt_col = tgt_table.get_column(col_name)
            if tgt_col:
                ts_type = _TS_TYPE.get(tgt_col.col_type, "unknown")
                lines.append(f"    {col_name}: undefined as unknown as {ts_type}, // TODO: no source mapping")
        lines.append("  };")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


# ── Helpers ───────────────────────────────────────────────────────────────────

def _to_pascal(name: str) -> str:
    return "".join(word.capitalize() for word in name.replace("-", "_").split("_"))


def _sa_col_type(col) -> str:
    t = col.col_type
    if t == ColumnType.VARCHAR:
        return f"String({col.max_length or 255})"
    if t == ColumnType.CHAR:
        return f"CHAR({col.max_length or 1})"
    if t == ColumnType.DECIMAL:
        return f"Numeric(precision={col.precision or 10}, scale={col.scale or 2})"
    if t == ColumnType.ENUM and col.enum_values:
        return "String(50)"
    return _SA_TYPE.get(t, "Text")


def _ts_cast(src_type: ColumnType, tgt_type: ColumnType, expr: str) -> str:
    if tgt_type in (ColumnType.INTEGER, ColumnType.BIGINT, ColumnType.SMALLINT):
        return f"Number({expr})"
    if tgt_type in (ColumnType.FLOAT, ColumnType.DOUBLE, ColumnType.DECIMAL):
        return f"parseFloat(String({expr}))"
    if tgt_type in (ColumnType.VARCHAR, ColumnType.TEXT, ColumnType.CHAR):
        return f"String({expr})"
    if tgt_type == ColumnType.BOOLEAN:
        return f"Boolean({expr})"
    if tgt_type in (ColumnType.DATE, ColumnType.DATETIME, ColumnType.TIMESTAMP):
        return f"new Date({expr})"
    return f"({expr} as unknown) as {_TS_TYPE.get(tgt_type, 'unknown')}"
